/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/XPPage` | `/XPPage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/calories` | `/calories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/fitness` | `/fitness`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/journal` | `/journal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/therapist` | `/therapist`; params?: Router.UnknownInputParams; } | { pathname: `/components/KoalaAnimations`; params?: Router.UnknownInputParams; } | { pathname: `/utils/wxp`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/XPPage` | `/XPPage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/calories` | `/calories`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/fitness` | `/fitness`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/journal` | `/journal`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/therapist` | `/therapist`; params?: Router.UnknownOutputParams; } | { pathname: `/components/KoalaAnimations`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/wxp`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/XPPage${`?${string}` | `#${string}` | ''}` | `/XPPage${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/calories${`?${string}` | `#${string}` | ''}` | `/calories${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/fitness${`?${string}` | `#${string}` | ''}` | `/fitness${`?${string}` | `#${string}` | ''}` | `${'/(home)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/journal${`?${string}` | `#${string}` | ''}` | `/journal${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/therapist${`?${string}` | `#${string}` | ''}` | `/therapist${`?${string}` | `#${string}` | ''}` | `/components/KoalaAnimations${`?${string}` | `#${string}` | ''}` | `/utils/wxp${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/XPPage` | `/XPPage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/calories` | `/calories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/fitness` | `/fitness`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/journal` | `/journal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/therapist` | `/therapist`; params?: Router.UnknownInputParams; } | { pathname: `/components/KoalaAnimations`; params?: Router.UnknownInputParams; } | { pathname: `/utils/wxp`; params?: Router.UnknownInputParams; };
    }
  }
}
